[package]
name = "randomness"
version = "1.0.0"
authors = []

[addresses]
RandHack = "8149732561160849438e7f91fe630088b4bda0ef91c2b7886b0e6f82e6d3388a"

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
